version: '3'
services:
  ngrok:
    image: wernight/ngrok
    environment:
    - NGROK_PORT=web:8080
    ports:
      - "4040:4040"
    links:
      - web
  redis:
    image: redis
    ports:
      - "6379:6379"
  web:
    build: .
    environment:
      - REDIS_HOSTNAME=redis
    ports:
      - "8080:8080"
    restart: unless-stopped
    links:
      - redis
    depends_on:
      - redis
